const type = {
  LOGIN_DATA: 'LOGIN_DATA',
  LOADING_PAGE: 'LOADING_PAGE',
  SET_TODO_LIST: 'SET_TODO_LIST',
  SET_ALL_TODOS: 'SET_ALL_TODOS',
  SET_TODO: 'SET_TODO',
  SET_TASK_ID: 'SET_TASK_ID'
}

export default type